server:
  port: 7005
spring:
  application:
    name: springcloud-zuul
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@localhost:7000/eureka
#springboot-feign
zuul:
  routes: #给服务配置路由
    user-service:
      path: /userService/**
    springboot-feign:
      path: /springboot-feign/**
  prefix: /proxy
  sensitive-headers: Cookie,Set-Cookie,Authorization #配置过滤敏感的请求头信息，设置为空就不会过滤
  add-host-header: true #设置为true重定向是会添加host请求头
  filterClassName:
    filter:
      disable: true
  PrelogFilter:
    pre:
      disable: true

management:
  endpoints:
    web:
      exposure:
        include: 'routes'

